# Generated by Django 5.2.4 on 2025-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
