# Generated by Django 5.2.4 on 2025-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_shop_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
