# Generated by Django 5.2.4 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutomer_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email_id', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.IntegerField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
