# Generated by Django 5.2.4 on 2026-02-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutomer_register',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
