# Generated by Django 5.2.4 on 2026-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_register', '0002_alter_cutomer_register_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutomer_register',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
